### ISSUE TITLE
Проблема с сохранением ссылки в avatar

### ISSUE THREAD

**Issue by vlolad** [PavelProjects/organizer#4]
В бд ограничение на 128 символов для аватарки. Многие прямые ссылки на картинки куда длиннее.

Можно:
1) Сохранять как-то картинки на сервер и прописывать локальный путь, сохранять его в бд (кажется, что это запарно)
2) Снять/увеличить ограничение

P.S. Я хотел создать пользователя с такой аватаркой: [shorturl.at/flrwz](https://sun9-75.userapi.com/impg/2p5Izzxv7eCHCibwJXNk5gdvs4lc7xrrfE1DUw/ApvbEGmeVaQ.jpg?size=1120x896&quality=96&sign=780cd31d3d5d2eda0d6eae0c7790e496&type=album)

**Comment by vlolad** [comment]
А СОЗДАЛ[ С ТАКОЙ](https://wiki.teamfortress.com/w/images/thumb/3/37/Spyfencingtauntkill.PNG/250px-Spyfencingtauntkill.PNG)

**Comment by PavelProjects** [comment]
На аватарки я бы пока забил на самом деле, но правильнее будет сделать так:
1) дать возможность грузить фото как с компа, так и ссылками
2) в обоих случаях копировать фотки в локальное хранилище и ссылаться на него
Те нужен как то ендпоинт для доступа к контенту
Мы его ещё не прорабатывали, поэтому я, бы пока отложил эту таску. Можно в notion создать такое задание с низким приоритетом.
